apiVersion: 1

deleteDatasources:
  - name: Sensors
    type: postgres

datasources:
  - name: Sensors
    uid: Sensors
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      postgresVersion: 1600
      sslmode: "disable"
      timescaledb: false