# Log ins Stdout für docker logs
log_dest stdout

persistence true
persistence_location /mosquitto/data/

# Offener Listener im LAN
listener 8883 0.0.0.0
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
allow_anonymous false
password_file /mosquitto/passwordfile