# Log ins Stdout für docker logs
log_dest stdout

persistence true
persistence_location /mosquitto/data/

# Offener Listener im LAN
listener 1883
# SSL Listener für das Internet
listener 8883 0.0.0.0
cafile /etc/ssl/certs/ca-certificates.crt
certfile /etc/letsencrypt/live/janlieder.de/fullchain.pem
keyfile /etc/letsencrypt/live/janlieder.de/privkey.pem
allow_anonymous false
password_file /mosquitto/passwordfile